channels:
- conda-forge
dependencies:
- python=3.11.6
- pip<=23.2.1
- pip:
  - mlflow==2.13.2
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.1
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.5.0
  - scipy==1.13.1
name: mlflow-env
